In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[1,2,3],[1,2,3]]
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
np.arange(0,11,2) # START - END - STEP

array([ 0,  2,  4,  6,  8, 10])

In [7]:
# np.zeros(3)
np.zeros((3,5)) # n of rows - n of cols

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.linspace(0,9,10) # Get x elements evenly spreaded around a and b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Identity matrix 

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand(5) # Elements distributed from 0 to 1

array([0.67151413, 0.11488593, 0.57060513, 0.12738681, 0.40686798])

In [12]:
np.random.rand(5, 5)

array([[0.28132889, 0.3573576 , 0.58823952, 0.01242402, 0.22557696],
       [0.78141413, 0.40220244, 0.36749667, 0.90708704, 0.68874292],
       [0.49139694, 0.04695252, 0.36575566, 0.12207114, 0.39946458],
       [0.72836224, 0.1036738 , 0.93783678, 0.15922692, 0.72462986],
       [0.4423381 , 0.90474396, 0.28562261, 0.1552604 , 0.60778087]])

In [13]:
# np.random.randn(2)
np.random.randn(4,4)

array([[ 1.18399779,  1.37099703, -0.34809448, -0.99836937],
       [-0.62373577, -2.26725638, -0.16499848,  1.28071899],
       [ 0.76427815,  0.21399121,  2.12810183, -0.43213116],
       [ 1.68598367,  0.10243771, -0.49651183, -0.58863744]])

In [14]:
# np.random.randint(1,100) # Get a random number from a to b
np.random.randint(1,100,10) # Get a random number from a to b

array([75, 97, 38, 21, 70, 33, 27, 58, 27,  5])

In [15]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
ranarr = np.random.randint(0,50,10)
ranarr

array([33, 21,  5, 42, 11, 35, 19, 10, 27, 44])

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ranarr.max()

44

In [19]:
ranarr.min()

5

In [20]:
ranarr.argmax() # Returns the index location of the max

9

In [21]:
ranarr.argmin() # Returns the index location of the min

2

In [22]:
# Get the spae of a vector
arr.shape

(25,)

In [23]:
arr = arr.reshape(5,5)

In [24]:
arr.shape

(5, 5)

In [25]:
arr.dtype

dtype('int32')

In [27]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

8

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [32]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [33]:
arr[:5]

array([0, 1, 2, 3, 4])

In [34]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [44]:
slice_of_arr[:] = 90
slice_of_arr

array([90, 90, 90, 90, 90, 90])

In [45]:
arr 

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [47]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr_copy = arr

In [49]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [50]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

Indexing and selection

In [62]:
arr_2d = np.array([[5,10,15],[35,40,45],[20,40,46]])

In [64]:
arr_2d

array([[ 5, 10, 15],
       [35, 40, 45],
       [20, 40, 46]])

In [65]:
arr_2d[0][2] # Array[fila][columna]

15

In [66]:
arr_2d[0] # fila - columna

array([ 5, 10, 15])

In [68]:
arr_2d[2,1] # fila - columna

40

In [71]:
arr_2d[:2,1:] # fila - columna

array([[10, 15],
       [40, 45]])

In [87]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
bool_arr = arr_2d > 20
bool_arr

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [89]:
arr_2d[bool_arr] # returns all values that are true

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [90]:
arr[arr>5]

array([6, 7, 8, 9])

In [91]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [92]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

#### Array Operations

In [93]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [95]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [97]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [98]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [99]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [100]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [101]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [103]:
np.max(arr)

9

In [104]:
arr.max()

9